"""Download every Taco Bell from OpenStreetMap (Overpass API) into tacobell.h.

    python tools/make_tacobell.py tacobell.h [--raw overpass.json] [--merge-m 60]

Only needs the standard library. Matches the brand tag (Wikidata Q752941) plus fast-food
places named "Taco Bell" that lack it, takes the centre of buildings/areas, merges points
closer than --merge-m (a shop mapped as both a node and a building), adds EXTRA, and
writes them sorted by latitude. With --raw, the Overpass response is saved to that file
and reused on later runs instead of querying again.
"""
import argparse, json, math, os, urllib.parse, urllib.request

URL = 'https://overpass-api.de/api/interpreter'
QUERY = """
[out:json][timeout:600];
(
  nwr["brand:wikidata"="Q752941"];
  nwr["amenity"~"^(fast_food|restaurant)$"]["name"~"^taco bell",i];
);
out center tags;
"""

# Locations missing from OpenStreetMap: (lat, lon, note)
EXTRA = [
    (42.347062, -71.088264, 'Boston, near Northeastern'),
]

# Tags that mean the place has shut
CLOSED_KEYS = ('disused:amenity', 'was:amenity', 'abandoned:amenity')


def fetch():
    data = urllib.parse.urlencode({'data': QUERY}).encode()
    req = urllib.request.Request(URL, data, {'User-Agent': 'tacobell-compass/1.0'})
    with urllib.request.urlopen(req, timeout=700) as r:
        return json.load(r)


def points(osm):
    out = []
    for el in osm['elements']:
        tags = el.get('tags', {})
        if any(k in tags for k in CLOSED_KEYS):
            continue
        c = el if 'lat' in el else el.get('center')
        if c:
            out.append((c['lat'], c['lon']))
    return out


def dist_m(a, b):
    p1, p2 = math.radians(a[0]), math.radians(b[0])
    h = (math.sin((p2 - p1) / 2) ** 2
         + math.cos(p1) * math.cos(p2) * math.sin(math.radians(b[1] - a[1]) / 2) ** 2)
    return 6371000 * 2 * math.asin(math.sqrt(h))


def merge(pts, radius_m):
    """Drop points within radius_m of one already kept (grid lookup, ~0.01 deg cells)."""
    cell = 0.01
    grid, kept = {}, []
    for p in pts:
        cx, cy = int(p[0] // cell), int(p[1] // cell)
        near = (q for dx in (-1, 0, 1) for dy in (-1, 0, 1) for q in grid.get((cx + dx, cy + dy), ()))
        if any(dist_m(p, q) < radius_m for q in near):
            continue
        grid.setdefault((cx, cy), []).append(p)
        kept.append(p)
    return kept


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('out')
    ap.add_argument('--raw', help='save the Overpass JSON here, or reuse it if it exists')
    ap.add_argument('--merge-m', type=float, default=60)
    args = ap.parse_args()

    if args.raw and os.path.exists(args.raw):
        with open(args.raw) as f:
            osm = json.load(f)
    else:
        osm = fetch()
        if args.raw:
            with open(args.raw, 'w') as f:
                json.dump(osm, f)

    found = points(osm)
    locs = merge(found, args.merge_m)
    notes = {}
    for lat, lon, note in EXTRA:
        if all(dist_m((lat, lon), q) >= args.merge_m for q in locs):
            locs.append((lat, lon))
            notes[(lat, lon)] = note
    locs.sort()

    with open(args.out, 'w') as f:
        f.write('// Generated by tools/make_tacobell.py from OpenStreetMap. Do not edit by hand.\n')
        f.write('#pragma once\n#include <stdint.h>\n\n')
        f.write(f'#define TACOBELL_COUNT {len(locs)}\n\n')
        f.write('// Interleaved {lat, lon} pairs. const places it in flash.\n')
        f.write('static const float TACOBELL_LOCATIONS[TACOBELL_COUNT][2] = {\n')
        for p in locs:
            note = f'   // {notes[p]}' if p in notes else ''
            f.write(f'  {{{p[0]:.6f}f, {p[1]:.6f}f}},{note}\n')
        f.write('};\n')
    print(f'{len(found)} from OSM, {len(locs)} after merging and extras -> {args.out}')


if __name__ == '__main__':
    main()
